# -*- coding: utf-8 -*-
import re
from typing import Dict, Any, List

def _get_type_info(raw_type: str) -> Dict[str, str]:
    cleaned = str(raw_type).lower().strip()
    mapping = {
        "string": {"ts": "string", "dart": "String", "sample": '"ejemplo"'},
        "str": {"ts": "string", "dart": "String", "sample": '"ejemplo"'},
        "text": {"ts": "string", "dart": "String", "sample": '"texto descriptivo"'},
        "varchar": {"ts": "string", "dart": "String", "sample": '"ejemplo"'},
        "int": {"ts": "number", "dart": "int", "sample": "10"},
        "integer": {"ts": "number", "dart": "int", "sample": "10"},
        "long": {"ts": "number", "dart": "int", "sample": "100"},
        "bigint": {"ts": "number", "dart": "int", "sample": "100"},
        "double": {"ts": "number", "dart": "double", "sample": "99.99"},
        "float": {"ts": "number", "dart": "double", "sample": "49.50"},
        "decimal": {"ts": "number", "dart": "double", "sample": "150.00"},
        "bool": {"ts": "boolean", "dart": "bool", "sample": "true"},
        "boolean": {"ts": "boolean", "dart": "bool", "sample": "true"},
        "date": {"ts": "string (YYYY-MM-DD)", "dart": "DateTime", "sample": '"2026-05-15"'},
        "datetime": {"ts": "string (ISO-8601)", "dart": "DateTime", "sample": '"2026-05-15T10:30:00"'},
        "timestamp": {"ts": "string (ISO-8601)", "dart": "DateTime", "sample": '"2026-05-15T10:30:00"'}
    }
    return mapping.get(cleaned, {"ts": "string", "dart": "String", "sample": '"ejemplo"'})

def get_plural_name(name: str) -> str:
    lower = name.lower()
    if lower.endswith("s"):
        return lower
    if lower.endswith("y") and len(lower) > 1 and lower[-2] not in "aeiou":
        return lower[:-1] + "ies"
    if lower.endswith("z"):
        return lower[:-1] + "ces"
    if lower.endswith("dad") or lower.endswith("cion") or lower.endswith("sion") or lower.endswith("tad"):
        return lower + "es"
    return lower + "s"

def generate_frontend_meta_prompt(
    graph_data: dict, 
    target_framework: str = "flutter", 
    theme: str = "dark"
) -> str:
    """
    Generates an exhaustive, high-precision, production-grade Meta-Prompt in Markdown
    for external LLMs (Claude 3.5 Sonnet, GPT-4o, Gemini 1.5 Pro, Cursor)
    to generate a complete Mobile Application (Flutter / React Native) or Web SPA
    consuming the Spring Boot 3 / Java 17 backend generated by ClassForge.
    """
    nodes = graph_data.get("nodes", []) if isinstance(graph_data, dict) else []
    edges = graph_data.get("edges", []) if isinstance(graph_data, dict) else []
    
    classes: Dict[str, Dict[str, Any]] = {}
    for node in nodes:
        node_type = (node.get("type") or node.get("shape") or "").lower().replace("uml-", "")
        if node_type in ["class", "abstract", "entity", "classnode"]:
            data = node.get("data", {})
            raw_name = data.get("name") or "Entity"
            clean_name = re.sub(r'[^a-zA-Z0-9_]', '', str(raw_name))
            if not clean_name or not clean_name[0].isalpha():
                clean_name = f"Entity{clean_name}"
            clean_name = clean_name[0].upper() + clean_name[1:]
            
            raw_attrs = data.get("attributes", [])
            parsed_attrs = []
            for attr in raw_attrs:
                if isinstance(attr, dict):
                    aname = attr.get("name", "")
                    atype = attr.get("type", "string")
                elif isinstance(attr, str):
                    cleaned = attr.lstrip("+-#~ ").strip()
                    if ":" in cleaned:
                        parts = cleaned.split(":", 1)
                        aname = parts[0].strip()
                        atype = parts[1].strip()
                    else:
                        aname = cleaned
                        atype = "string"
                else:
                    continue
                aname = re.sub(r'[^a-zA-Z0-9_]', '', str(aname))
                if not aname or aname.lower() in ["id", "_id", "createdat", "updatedat", "created_at", "updated_at"]:
                    continue
                aname = aname[0].lower() + aname[1:]
                type_info = _get_type_info(atype)
                parsed_attrs.append({
                    "name": aname,
                    "ts_type": type_info["ts"],
                    "dart_type": type_info["dart"],
                    "sample": type_info["sample"]
                })
            
            plural_path = get_plural_name(clean_name)
            classes[str(node.get("id"))] = {
                "name": clean_name,
                "endpoint_path": plural_path,
                "attributes": parsed_attrs,
                "relations": [],
                "parent_name": None
            }
            
    for edge in edges:
        source_val = edge.get("source")
        target_val = edge.get("target")
        source_id = str(source_val if isinstance(source_val, str) else (source_val.get("cell") if isinstance(source_val, dict) else str(source_val or "")))
        target_id = str(target_val if isinstance(target_val, str) else (target_val.get("cell") if isinstance(target_val, dict) else str(target_val or "")))
        rel_type = (edge.get("type") or edge.get("shape") or "").lower().replace("uml-", "")
        
        if source_id in classes and target_id in classes:
            if rel_type in ["inheritance", "realization"]:
                classes[source_id]["parent_name"] = classes[target_id]["name"]
            elif rel_type in ["composition", "aggregation", "association"]:
                # Source has OneToMany to target; Target has ManyToOne to source
                classes[source_id]["relations"].append({
                    "type": "OneToMany",
                    "target_name": classes[target_id]["name"],
                    "field_name": classes[target_id]["name"][0].lower() + classes[target_id]["name"][1:] + "s",
                    "target_endpoint": classes[target_id]["endpoint_path"]
                })
                classes[target_id]["relations"].append({
                    "type": "ManyToOne",
                    "target_name": classes[source_id]["name"],
                    "field_name": classes[source_id]["name"][0].lower() + classes[source_id]["name"][1:],
                    "foreign_key": classes[source_id]["name"][0].lower() + classes[source_id]["name"][1:] + "Id",
                    "target_endpoint": classes[source_id]["endpoint_path"]
                })

    framework_normalized = target_framework.lower().strip()
    theme_normalized = theme.lower().strip()
    
    # ─── Framework Instructions ────────────────────────────────────
    if framework_normalized in ["flutter", "dart"]:
        framework_title = "Flutter 3.x (Dart 3) Clean Architecture Mobile App"
        framework_instructions = """- **Tecnología**: Flutter 3.x, Dart 3.x con Clean Architecture / Feature-First structure.
- **Gestión de Estado**: `flutter_riverpod` (v2.5+) o `provider` para manejo reactivo de listas, filtros y estados asíncronos (`AsyncValue`).
- **Cliente HTTP y Red**:
  - `dio` (v5.4+) con interceptor de logging y manejo de errores.
  - **Configuración de Base URL según plataforma**:
    - Emulador Android: `http://10.0.2.2:8080/api/v1`
    - Simulador iOS / Web: `http://localhost:8080/api/v1`
    - Dispositivo Físico: `http://TU_IP_LOCAL:8080/api/v1`
- **UI & Diseño Mobile**: Material 3 (`useMaterial3: true`), Google Fonts (Poppins / Inter), animaciones sutiles, pull-to-refresh (`RefreshIndicator`), swipe-to-delete (`Dismissible`), FloatingActionButton para crear, y esqueleto de carga con `shimmer`.
- **Estructura de Directorios Recomendada**:
  ```
  lib/
  ├── core/
  │   ├── constants/api_constants.dart
  │   ├── network/dio_client.dart
  │   ├── theme/app_theme.dart
  │   └── errors/app_exception.dart
  ├── models/                 # Modelos con fromJson, toJson, copyWith
  ├── services/               # Clases de servicio con llamadas Dio CRUD
  ├── providers/              # StateNotifier / Riverpod providers
  ├── screens/
  │   ├── home/dashboard_screen.dart
  │   └── [entidad]/
  │       ├── [entidad]_list_screen.dart
  │       ├── [entidad]_form_screen.dart
  │       └── [entidad]_detail_screen.dart
  ├── widgets/                # Componentes reutilizables (CustomTextField, EntityPickerBottomSheet, ShimmerCard)
  └── main.dart
  ```
- **Dependencias en `pubspec.yaml`**:
  ```yaml
  dependencies:
    flutter:
      sdk: flutter
    flutter_riverpod: ^2.5.1
    dio: ^5.4.3+1
    intl: ^0.19.0
    shimmer: ^3.0.0
    google_fonts: ^6.2.1
    fluttertoast: ^8.2.8
  ```"""
    elif framework_normalized in ["react-native", "reactnative", "expo"]:
        framework_title = "React Native (Expo / TypeScript) Modern Mobile App"
        framework_instructions = """- **Tecnología**: React Native 0.74+ con Expo (Expo Router v3 o React Navigation v6), TypeScript estricto.
- **Gestión de Estado y Servidor**: `@tanstack/react-query` (TanStack Query v5) para cacheo inteligente, refresco en segundo plano y mutaciones optimistas + `zustand` para estado global ligero.
- **Cliente HTTP y Red**:
  - `axios` configurado con baseURL condicional:
    ```typescript
    import { Platform } from 'react-native';
    const API_BASE_URL = Platform.OS === 'android' 
      ? 'http://10.0.2.2:8080/api/v1' 
      : 'http://localhost:8080/api/v1';
    ```
- **UI & Estilizado Mobile**: `NativeWind` (Tailwind CSS para React Native) o `StyleSheet` con paleta moderna, `lucide-react-native` para íconos, `react-native-toast-message` para notificaciones flotantes, y `FlashList` / `FlatList` con `refreshControl`.
- **Estructura de Directorios Recomendada**:
  ```
  src/
  ├── api/
  │   ├── apiClient.ts
  │   └── config.ts
  ├── types/                  # Interfaces RequestDTO y ResponseDTO
  ├── services/               # Funciones CRUD tipadas con Axios
  ├── hooks/                  # Custom hooks useEntities(), useCreateEntity() con React Query
  ├── navigation/             # BottomTabNavigator y StackNavigator
  ├── screens/
  │   ├── DashboardScreen.tsx
  │   └── [Entidad]/
  │       ├── [Entidad]ListScreen.tsx
  │       ├── [Entidad]FormScreen.tsx
  │       └── [Entidad]DetailScreen.tsx
  ├── components/             # InputField, RelationPickerModal, EmptyState, LoadingSkeleton
  └── App.tsx
  ```
- **Dependencias en `package.json`**:
  ```json
  {
    "dependencies": {
      "expo": "~51.0.0",
      "react": "18.2.0",
      "react-native": "0.74.0",
      "@tanstack/react-query": "^5.28.0",
      "axios": "^1.6.8",
      "zustand": "^4.5.2",
      "lucide-react-native": "^0.360.0",
      "react-native-toast-message": "^2.2.0",
      "@react-navigation/native": "^6.1.17",
      "@react-navigation/bottom-tabs": "^6.5.20",
      "@react-navigation/native-stack": "^6.9.26"
    }
  }
  ```"""
    elif framework_normalized == "angular":
        framework_title = "Angular 17+ (Standalone Signals & RxJS) Enterprise SPA"
        framework_instructions = """- **Technology Stack**: Angular 17+ (Standalone Components, NO NgModules), TypeScript, Tailwind CSS, Angular Signals.
- **State & Architecture**: Reactive services with Angular Signals (`signal()`, `computed()`), `HttpClient` with RxJS.
- **Forms**: ReactiveFormsModule (`FormGroup`, `FormControl`, `Validators`).
- **Routing**: Angular Router with lazy loading routes per feature module."""
    elif framework_normalized == "vue":
        framework_title = "Vue 3 (Composition API / Pinia) Modern Web App"
        framework_instructions = """- **Technology Stack**: Vue 3 (Vite), `<script setup>` syntax, TypeScript, Tailwind CSS, Pinia, Axios.
- **State & Routing**: Vue Router 4, Pinia stores for state and entity caching.
- **Forms**: `v-model` with form validation feedback.
- **HTTP Client**: Axios instance configured with `baseURL: 'http://localhost:8080/api/v1'`."""
    elif framework_normalized == "vanilla":
        framework_title = "Vanilla HTML5 / JavaScript (ES Modules) Lightweight Web App"
        framework_instructions = """- **Technology Stack**: Modern Semantic HTML5, Vanilla JavaScript (ES Modules, async/await), Tailwind CSS (via CDN).
- **Structure**: Modular JavaScript structure (`api.js`, `components.js`, `app.js`).
- **HTTP Client**: Native `fetch()` wrapper with JSON parsing and standardized error handling."""
    else: # Default react
        framework_title = "React 18+ (Vite / TypeScript / Tailwind) Professional Web SPA"
        framework_instructions = """- **Technology Stack**: React 18+ (Vite), TypeScript, Tailwind CSS, Lucide React icons, Axios.
- **State & Routing**: React Router v6, React Context or Zustand for global notifications/modal state.
- **Forms**: Controlled components or React Hook Form with validation on submit.
- **HTTP Client**: Axios instance configured with `baseURL: 'http://localhost:8080/api/v1'`, request/response interceptors with error handling."""

    palette_instructions = """- **Tema Visual**: Modo Oscuro Enterprise (ClassForge Dark Aesthetic).
  - Fondo Principal: `#0F172A` (Slate 900)
  - Superficies y Tarjetas: `#1E293B` (Slate 800)
  - Bordes e Inputs: `#334155` (Slate 700)
  - Acento Primario: `#256BE4` (Electric Blue) con hover/active `#1A4FB0`
  - Éxito / Confirmación: `#10B981` (Emerald Green)
  - Peligro / Eliminación: `#EF4444` (Ruby Red)
  - Textos: `#F1F5F9` (Slate 100) primario, `#94A3B8` (Slate 400) secundario.""" if theme_normalized == "dark" else """- **Tema Visual**: Modo Claro Limpio y Moderno.
  - Fondo Principal: `#F8FAFC` (Slate 50)
  - Superficies y Tarjetas: `#FFFFFF` (Pure White) con sombras suaves `shadow-sm`
  - Bordes e Inputs: `#E2E8F0` (Slate 200)
  - Acento Primario: `#2563EB` (Royal Blue)
  - Éxito / Confirmación: `#10B981` (Emerald)
  - Peligro / Eliminación: `#EF4444` (Red)
  - Textos: `#0F172A` (Slate 900) primario, `#64748B` (Slate 500) secundario."""

    entities_doc = []
    for cls in classes.values():
        name = cls["name"]
        endpoint = cls["endpoint_path"]
        attrs = cls["attributes"]
        relations = cls["relations"]
        parent = cls.get("parent_name")
        
        sample_request_fields = {}
        sample_response_fields = {"id": 1}
        for a in attrs:
            val_sample = "ejemplo" if "string" in a["ts_type"] else (10 if "number" in a["ts_type"] else True)
            sample_request_fields[a["name"]] = val_sample
            sample_response_fields[a["name"]] = val_sample
            
        rel_specs = []
        for r in relations:
            if r["type"] == "ManyToOne":
                sample_request_fields[r["foreign_key"]] = 1
                sample_response_fields[r["field_name"]] = {"id": 1, "name": f"Parent {r['target_name']}"}
                rel_specs.append(f"  - **Pertenece a `{r['target_name']}` (@ManyToOne)**: El formulario de creación/edición de `{name}` DEBE incluir un selector (Dropdown o Bottom Sheet Modal) cargado dinámicamente desde `GET /api/v1/{r['target_endpoint']}` para seleccionar `{r['foreign_key']}`.")
            elif r["type"] == "OneToMany":
                sample_response_fields[r["field_name"]] = []
                rel_specs.append(f"  - **Tiene muchos `{r['target_name']}` (@OneToMany)**: En la vista de detalle de `{name}`, mostrar una sub-lista o tarjetas con los elementos hijos `{r['field_name']}`.")
                
        rel_str = "\n".join(rel_specs) if rel_specs else "  - *Sin relaciones foráneas directas.*"
        parent_str = f"\n  - *Hereda de*: `{parent}` (Herencia `@Inheritance(strategy = InheritanceType.JOINED)`)" if parent else ""
        
        entity_section = f"""### Entidad: `{name}`
- **Endpoint Base**: `http://localhost:8080/api/v1/{endpoint}`{parent_str}
- **Atributos de Dominio**:
{chr(10).join([f"  - `{a['name']}`: `{a['ts_type']}` (Dart: `{a['dart_type']}`)" for a in attrs]) or "  - *(Solo ID autogenerado)*"}
- **Relaciones de Dominio**:
{rel_str}
- **Contratos REST CRUD**:
  - `GET /api/v1/{endpoint}` ➔ Listar todos los registros (Respuesta: `List<{name}ResponseDTO>`)
  - `GET /api/v1/{endpoint}/{{id}}` ➔ Obtener un registro por ID
  - `POST /api/v1/{endpoint}` ➔ Crear nuevo registro (Payload JSON: `{name}RequestDTO`, HTTP 201 Created)
  - `PUT /api/v1/{endpoint}/{{id}}` ➔ Actualizar registro existente (Payload JSON: `{name}RequestDTO`, HTTP 200 OK)
  - `DELETE /api/v1/{endpoint}/{{id}}` ➔ Eliminar registro por ID (HTTP 204 No Content)
- **Ejemplo JSON Request Payload (`POST`/`PUT`)**:
```json
{sample_request_fields}
```
- **Ejemplo JSON Response Payload (`GET`)**:
```json
{sample_response_fields}
```"""
        entities_doc.append(entity_section)
        
    all_entities_str = "\n\n".join(entities_doc) if entities_doc else "*(No se definieron clases en el diagrama)*"
    
    prompt = f"""# Prompt para Generación de Aplicación Frontend / Mobile Profesional
## Objetivo: Construir {framework_title}

Actúa como un **Lead Mobile & Frontend Architect y UI/UX Senior Specialist**. Tu misión es construir una aplicación completa, modular, escalable y 100% funcional que consuma el backend Spring Boot 3 / Java 17 generado por ClassForge.

---

## 🛠️ Stack Técnico y Configuración de Arquitectura
{framework_instructions}

---

## 🎨 Paleta de Diseño y Guía de Estilo Visual
{palette_instructions}
- **Diseño Ergonómico**: Componentes táctiles amplios (mínimo 48x48 dp de área táctil en móvil), tipografía legible, micro-interacciones suaves.
- **Feedback Inmediato**: Estados de carga (*loaders* / *shimmers*), diálogos de confirmación antes de eliminar, y notificaciones toast ante éxitos o fallos de red.

---

## 📡 Especificación Exhaustiva de Contratos API REST
El backend Spring Boot 3 se ejecuta con prefijo `/api/v1/` y cuenta con CORS global habilitado.

{all_entities_str}

---

## 📋 Requerimientos de Pantallas y Experiencia de Usuario (UX)

Para cada una de las entidades del modelo de dominio, debes generar las siguientes pantallas y flujos:

### 1. Pantalla de Listado Principal (Master List)
- Barra superior con **Buscador en tiempo real** (filtrado local/remoto con debounce).
- Lista optimizada (`ListView.builder` en Flutter o `FlatList` / `FlashList` en React Native) mostrando tarjetas ordenadas con los campos clave de la entidad.
- **Gesto Pull-to-Refresh**: Al deslizar hacia abajo, refrescar la lista desde la API.
- **Gesto Swipe-to-Delete** (o botón de borrado): Permite eliminar rápidamente con diálogo de confirmación.
- **Botón Flotante de Acción (FAB `+`)**: En la esquina inferior derecha para abrir la pantalla/modal de creación.
- **Estado de Carga (Skeleton/Shimmer)**: Animación mientras se realiza la petición `GET`.
- **Estado Vacío (Empty State)**: Ilustración con ícono y botón *"Crear el primer registro"* si no hay datos.

### 2. Pantalla / Modal de Formulario (Creación y Edición)
- Inputs apropiados para cada tipo de dato (texto, email, numérico, selector de fecha con DatePicker).
- Validación de formularios reactiva: campos requeridos en rojo, mensajes de error claros.
- **Para Relaciones `@ManyToOne`**: Selector dinámico (Dropdown o Bottom Sheet Selector) que consulta `GET /api/v1/{'{padre}'}` para listar las opciones disponibles y asociar la clave foránea.
- Botón *"Guardar"* con indicador de progreso circular mientras envía el payload `POST` o `PUT`.

### 3. Pantalla de Detalle (Detail View)
- Tarjeta estilizada con todos los campos de la entidad, fechas de auditoría (`createdAt`, `updatedAt`) formateadas.
- Si tiene relaciones `@OneToMany`, sub-lista con los registros hijos vinculados.
- Botones de acción rápida: *"Editar"* y *"Eliminar"*.

### 4. Navegación y Dashboard
- Menú de navegación principal (Bottom Navigation Bar o Drawer lateral) que permita alternar entre las diferentes entidades del sistema y un Dashboard principal con contadores resumidos.

---

## 📦 Instrucciones de Entrega del Código
1. Proporciona el código **COMPLETO**, sin omitir funciones ni colocar marcadores como `"// TODO: Implementar aquí"`.
2. Incluye la estructura de directorios y los archivos con sus rutas relativas exactas.
3. Incluye los archivos de configuración requeridos (`pubspec.yaml` para Flutter, `package.json` para React Native/Web) con las versiones exactas de las librerías.
4. Proporciona las instrucciones precisas para correr el proyecto en emuladores Android, iOS o navegador.
"""
    return prompt

