# -*- coding: utf-8 -*-
"""
Spring Boot 3 + Java 17 Production-Grade Code Templates.
Conforms strictly to Clean Code, SOLID Principles, and Spring Boot 3 Best Practices.
"""

POM_XML = """<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>{package_name}</groupId>
    <artifactId>classforge-generated-backend</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>ClassForge Generated Backend</name>
    <description>Enterprise Clean Architecture Spring Boot 3 Backend generated by ClassForge</description>

    <properties>
        <java.version>17</java.version>
        <springdoc.version>2.6.0</springdoc.version>
    </properties>

    <dependencies>
        <!-- Spring Boot Starters -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- Swagger / OpenAPI 3 Documentation -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${{springdoc.version}}</version>
        </dependency>

        <!-- Database Drivers -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Lombok Developer Productivity -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
"""

APPLICATION_YML = """# ===================================================================
# ClassForge Spring Boot 3 Application Configuration
# ===================================================================
spring:
  application:
    name: classforge-backend
  
  # Default datasource: H2 In-Memory for instant local execution
  datasource:
    url: jdbc:h2:mem:classforgedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# SpringDoc / Swagger OpenAPI UI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
"""

MAIN_APPLICATION = """package {package_name};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main Application Entry Point.
 * Generated with Clean Architecture standards by ClassForge.
 */
@SpringBootApplication
public class MainApplication {{

    public static void main(String[] args) {{
        SpringApplication.run(MainApplication.class, args);
    }}
}}
"""

OPENAPI_CONFIG = """package {package_name}.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI 3 / Swagger Documentation Configuration.
 */
@Configuration
public class OpenApiConfig {{

    @Bean
    public OpenAPI customOpenAPI() {{
        return new OpenAPI()
                .info(new Info()
                        .title("ClassForge REST API")
                        .version("1.0.0")
                        .description("Documentación interactiva de la API RESTful generada automáticamente por ClassForge.")
                        .contact(new Contact()
                                .name("ClassForge Developer Team")
                                .url("https://classforge.dev"))
                        .license(new License()
                                .name("Apache 2.0")
                                .url("https://www.apache.org/licenses/LICENSE-2.0")));
    }}
}}
"""

CORS_CONFIG = """package {package_name}.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * Global Cross-Origin Resource Sharing (CORS) Configuration.
 * Enables seamless integration with Web and Mobile clients (Flutter, React Native, React, Angular, Vue).
 */
@Configuration
public class CorsConfig implements WebMvcConfigurer {{

    @Override
    public void addCorsMappings(CorsRegistry registry) {{
        registry.addMapping("/**")
                .allowedOriginPatterns("*")
                .allowedMethods("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
                .allowedHeaders("*")
                .allowCredentials(false)
                .maxAge(3600);
    }}
}}
"""

RESOURCE_NOT_FOUND_EXCEPTION = """package {package_name}.exceptions;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * Exception thrown when a requested domain resource is not found.
 */
@ResponseStatus(HttpStatus.NOT_FOUND)
public class ResourceNotFoundException extends RuntimeException {{

    public ResourceNotFoundException(String message) {{
        super(message);
    }}

    public ResourceNotFoundException(String resourceName, String fieldName, Object fieldValue) {{
        super(String.format("%s no encontrado con %s : '%s'", resourceName, fieldName, fieldValue));
    }}
}}
"""

BAD_REQUEST_EXCEPTION = """package {package_name}.exceptions;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * Exception thrown when a business rule or validation fails.
 */
@ResponseStatus(HttpStatus.BAD_REQUEST)
public class BadRequestException extends RuntimeException {{

    public BadRequestException(String message) {{
        super(message);
    }}
}}
"""

ERROR_RESPONSE_DTO = """package {package_name}.exceptions;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Standard Error Response Payload for REST API.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ErrorResponseDTO {{

    private LocalDateTime timestamp;
    private int status;
    private String error;
    private String message;
    private String path;
    private Map<String, String> validationErrors;
}}
"""

GLOBAL_EXCEPTION_HANDLER = """package {package_name}.exceptions;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Global REST Exception Handler.
 * Intercepts domain exceptions and returns standardized HTTP error responses.
 */
@RestControllerAdvice
public class GlobalExceptionHandler {{

    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<ErrorResponseDTO> handleResourceNotFoundException(
            ResourceNotFoundException ex, 
            HttpServletRequest request) {{
        
        ErrorResponseDTO error = ErrorResponseDTO.builder()
                .timestamp(LocalDateTime.now())
                .status(HttpStatus.NOT_FOUND.value())
                .error(HttpStatus.NOT_FOUND.getReasonPhrase())
                .message(ex.getMessage())
                .path(request.getRequestURI())
                .build();
        return new ResponseEntity<>(error, HttpStatus.NOT_FOUND);
    }}

    @ExceptionHandler(BadRequestException.class)
    public ResponseEntity<ErrorResponseDTO> handleBadRequestException(
            BadRequestException ex, 
            HttpServletRequest request) {{
        
        ErrorResponseDTO error = ErrorResponseDTO.builder()
                .timestamp(LocalDateTime.now())
                .status(HttpStatus.BAD_REQUEST.value())
                .error(HttpStatus.BAD_REQUEST.getReasonPhrase())
                .message(ex.getMessage())
                .path(request.getRequestURI())
                .build();
        return new ResponseEntity<>(error, HttpStatus.BAD_REQUEST);
    }}

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponseDTO> handleValidationExceptions(
            MethodArgumentNotValidException ex, 
            HttpServletRequest request) {{
        
        Map<String, String> errors = new HashMap<>();
        ex.getBindingResult().getAllErrors().forEach((error) -> {{
            String fieldName = ((FieldError) error).getField();
            String errorMessage = error.getDefaultMessage();
            errors.put(fieldName, errorMessage);
        }});

        ErrorResponseDTO error = ErrorResponseDTO.builder()
                .timestamp(LocalDateTime.now())
                .status(HttpStatus.BAD_REQUEST.value())
                .error("Validation Failed")
                .message("Uno o más campos contienen valores no válidos.")
                .validationErrors(errors)
                .path(request.getRequestURI())
                .build();
        return new ResponseEntity<>(error, HttpStatus.BAD_REQUEST);
    }}

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponseDTO> handleGlobalException(
            Exception ex, 
            HttpServletRequest request) {{
        
        ErrorResponseDTO error = ErrorResponseDTO.builder()
                .timestamp(LocalDateTime.now())
                .status(HttpStatus.INTERNAL_SERVER_ERROR.value())
                .error(HttpStatus.INTERNAL_SERVER_ERROR.getReasonPhrase())
                .message("Ocurrió un error inesperado en el servidor: " + ex.getMessage())
                .path(request.getRequestURI())
                .build();
        return new ResponseEntity<>(error, HttpStatus.INTERNAL_SERVER_ERROR);
    }}
}}
"""

ENTITY_TEMPLATE = """package {package_name}.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA Entity: {class_name}
 * Table: {table_name}
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "{table_name}")
{inheritance_annotation}
public class {class_name} {extends_clause} {{
{fields}
}}
"""

REPOSITORY_TEMPLATE = """package {package_name}.repositories;

import {package_name}.entities.{class_name};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA Repository for {class_name}.
 */
@Repository
public interface {class_name}Repository extends JpaRepository<{class_name}, Long> {{
}}
"""

DTO_REQUEST_TEMPLATE = """package {package_name}.dto;

import jakarta.validation.constraints.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for creating or updating a {class_name}.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class {class_name}RequestDTO {{
{fields}
}}
"""

DTO_RESPONSE_TEMPLATE = """package {package_name}.dto;

import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for returning {class_name} representations.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class {class_name}ResponseDTO {{

    private Long id;
{fields}
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}}
"""

MAPPER_TEMPLATE = """package {package_name}.mappers;

import {package_name}.entities.{class_name};
import {package_name}.dto.{class_name}RequestDTO;
import {package_name}.dto.{class_name}ResponseDTO;
import org.springframework.stereotype.Component;

/**
 * Dedicated Mapper for converting between {class_name} Entity and DTOs.
 * Complies with the Single Responsibility Principle (SRP).
 */
@Component
public class {class_name}Mapper {{

    public {class_name} toEntity({class_name}RequestDTO dto) {{
        if (dto == null) {{
            return null;
        }}
        {class_name} entity = new {class_name}();
{map_to_entity_fields}
        return entity;
    }}

    public {class_name}ResponseDTO toResponseDTO({class_name} entity) {{
        if (entity == null) {{
            return null;
        }}
        {class_name}ResponseDTO dto = new {class_name}ResponseDTO();
        dto.setId(entity.getId());
{map_to_dto_fields}
        dto.setCreatedAt(entity.getCreatedAt());
        dto.setUpdatedAt(entity.getUpdatedAt());
        return dto;
    }}

    public void updateEntityFromDTO({class_name}RequestDTO dto, {class_name} entity) {{
        if (dto == null || entity == null) {{
            return;
        }}
{update_entity_fields}
    }}
}}
"""

SERVICE_INTERFACE_TEMPLATE = """package {package_name}.services;

import {package_name}.dto.{class_name}RequestDTO;
import {package_name}.dto.{class_name}ResponseDTO;

import java.util.List;

/**
 * Business Service Interface for managing {class_name} domain operations.
 */
public interface {class_name}Service {{

    List<{class_name}ResponseDTO> findAll();

    {class_name}ResponseDTO findById(Long id);

    {class_name}ResponseDTO create({class_name}RequestDTO requestDTO);

    {class_name}ResponseDTO update(Long id, {class_name}RequestDTO requestDTO);

    void deleteById(Long id);
}}
"""

SERVICE_IMPL_TEMPLATE = """package {package_name}.services.impl;

import {package_name}.entities.{class_name};
import {package_name}.dto.{class_name}RequestDTO;
import {package_name}.dto.{class_name}ResponseDTO;
import {package_name}.exceptions.ResourceNotFoundException;
import {package_name}.mappers.{class_name}Mapper;
import {package_name}.repositories.{class_name}Repository;
import {package_name}.services.{class_name}Service;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Service Implementation for {class_name}.
 * Handles transactional domain logic, entity mappings, and exception handling.
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional
public class {class_name}ServiceImpl implements {class_name}Service {{

    private final {class_name}Repository repository;
    private final {class_name}Mapper mapper;

    @Override
    @Transactional(readOnly = true)
    public List<{class_name}ResponseDTO> findAll() {{
        log.debug("Recuperando todas las entidades de {class_name}");
        return repository.findAll()
                .stream()
                .map(mapper::toResponseDTO)
                .collect(Collectors.toList());
    }}

    @Override
    @Transactional(readOnly = true)
    public {class_name}ResponseDTO findById(Long id) {{
        log.debug("Buscando {class_name} con ID: {{}}", id);
        return repository.findById(id)
                .map(mapper::toResponseDTO)
                .orElseThrow(() -> new ResourceNotFoundException("{class_name}", "id", id));
    }}

    @Override
    public {class_name}ResponseDTO create({class_name}RequestDTO requestDTO) {{
        log.info("Creando nuevo {class_name}");
        {class_name} entity = mapper.toEntity(requestDTO);
        {class_name} savedEntity = repository.save(entity);
        log.info("{class_name} creado exitosamente con ID: {{}}", savedEntity.getId());
        return mapper.toResponseDTO(savedEntity);
    }}

    @Override
    public {class_name}ResponseDTO update(Long id, {class_name}RequestDTO requestDTO) {{
        log.info("Actualizando {class_name} con ID: {{}}", id);
        {class_name} existingEntity = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("{class_name}", "id", id));

        mapper.updateEntityFromDTO(requestDTO, existingEntity);
        {class_name} updatedEntity = repository.save(existingEntity);
        log.info("{class_name} actualizado exitosamente con ID: {{}}", updatedEntity.getId());
        return mapper.toResponseDTO(updatedEntity);
    }}

    @Override
    public void deleteById(Long id) {{
        log.warn("Eliminando {class_name} con ID: {{}}", id);
        if (!repository.existsById(id)) {{
            throw new ResourceNotFoundException("{class_name}", "id", id);
        }}
        repository.deleteById(id);
        log.info("{class_name} con ID: {{}} eliminado con éxito", id);
    }}
}}
"""

CONTROLLER_TEMPLATE = """package {package_name}.controllers;

import {package_name}.dto.{class_name}RequestDTO;
import {package_name}.dto.{class_name}ResponseDTO;
import {package_name}.services.{class_name}Service;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST Controller for managing {class_name} resources.
 */
@RestController
@RequestMapping("/api/v1/{url_path}")
@RequiredArgsConstructor
@Tag(name = "{class_name}", description = "Endpoints de gestión para {class_name}")
public class {class_name}Controller {{

    private final {class_name}Service service;

    @Operation(summary = "Listar todos los {class_name}", description = "Devuelve una lista completa de registros de {class_name}.")
    @ApiResponses(value = {{
            @ApiResponse(responseCode = "200", description = "Lista obtenida con éxito")
    }})
    @GetMapping
    public ResponseEntity<List<{class_name}ResponseDTO>> findAll() {{
        return ResponseEntity.ok(service.findAll());
    }}

    @Operation(summary = "Obtener {class_name} por ID", description = "Recupera un registro específico a partir de su ID único.")
    @ApiResponses(value = {{
            @ApiResponse(responseCode = "200", description = "Registro encontrado con éxito"),
            @ApiResponse(responseCode = "404", description = "Registro no encontrado")
    }})
    @GetMapping("/{{id}}")
    public ResponseEntity<{class_name}ResponseDTO> findById(@PathVariable Long id) {{
        return ResponseEntity.ok(service.findById(id));
    }}

    @Operation(summary = "Crear nuevo {class_name}", description = "Crea y persiste un nuevo registro con los datos validados.")
    @ApiResponses(value = {{
            @ApiResponse(responseCode = "201", description = "Registro creado exitosamente"),
            @ApiResponse(responseCode = "400", description = "Datos de solicitud no válidos")
    }})
    @PostMapping
    public ResponseEntity<{class_name}ResponseDTO> create(@Valid @RequestBody {class_name}RequestDTO requestDTO) {{
        return new ResponseEntity<>(service.create(requestDTO), HttpStatus.CREATED);
    }}

    @Operation(summary = "Actualizar {class_name} existente", description = "Modifica un registro existente mediante su ID.")
    @ApiResponses(value = {{
            @ApiResponse(responseCode = "200", description = "Registro actualizado exitosamente"),
            @ApiResponse(responseCode = "404", description = "Registro no encontrado"),
            @ApiResponse(responseCode = "400", description = "Datos de actualización no válidos")
    }})
    @PutMapping("/{{id}}")
    public ResponseEntity<{class_name}ResponseDTO> update(
            @PathVariable Long id, 
            @Valid @RequestBody {class_name}RequestDTO requestDTO) {{
        return ResponseEntity.ok(service.update(id, requestDTO));
    }}

    @Operation(summary = "Eliminar {class_name} por ID", description = "Elimina permanentemente un registro por su ID.")
    @ApiResponses(value = {{
            @ApiResponse(responseCode = "204", description = "Registro eliminado con éxito"),
            @ApiResponse(responseCode = "404", description = "Registro no encontrado")
    }})
    @DeleteMapping("/{{id}}")
    public ResponseEntity<Void> deleteById(@PathVariable Long id) {{
        service.deleteById(id);
        return ResponseEntity.noContent().build();
    }}
}}
"""

PROJECT_README_MD = """# 🚀 {project_name} - Backend Spring Boot 3

Proyecto backend generado automáticamente por **ClassForge** siguiendo las normas y estándares de la industria para **Java 17 / Spring Boot 3** (Google Java Style Guide y Spring Framework Conventions), Clean Architecture y Clean Code.

---

## 🏗️ Estructura del Proyecto

```
src/main/java/{base_path}/
├── config/                  # Configuraciones globales (OpenAPI 3 Swagger, CORS)
├── controllers/             # Controladores RESTful (/api/v1/...) con Swagger Tags y Códigos HTTP
├── domain/ / entities/      # Entidades JPA con auditoría (createdAt, updatedAt) y llaves foráneas
├── dto/                     # DTOs de Petición (validaciones Jakarta) y Respuesta (@Schema)
├── exceptions/              # Manejador Global (@RestControllerAdvice) y Excepciones
├── mappers/                 # Mappers dedicados (Single Responsibility Principle)
├── repositories/            # Interfaces Spring Data JPA
├── services/                # Interfaces y Lógica de Negocio Transaccional (@Transactional, @Slf4j)
└── MainApplication.java     # Punto de entrada de la aplicación Spring Boot
```

---

## 💻 Ejecución Inmediata en Visual Studio Code (VS Code)

Este proyecto está pre-configurado para abrirse y ejecutarse sin fricción en **VS Code**:

1. **Abre la carpeta en VS Code**:
   Abre VS Code y selecciona `Archivo > Abrir Carpeta...` eligiendo esta carpeta descomprimida.
2. **Extensiones Recomendadas**:
   VS Code detectará automáticamente el archivo `.vscode/extensions.json` y te sugerirá instalar:
   - *Extension Pack for Java* (Microsoft)
   - *Spring Boot Extension Pack* (VMware)
   - *Lombok Annotations Support for VS Code*
3. **Ejecutar el Proyecto**:
   - **Opción A (Terminal con 1 solo comando)**:
     Abre la terminal integrada (Ctrl + ~ o Terminal > Nueva Terminal) y ejecuta:
     ```cmd
     .\\run.bat
     ```
     *(En Linux o macOS ejecuta `./run.sh`)*. El script auto-detectará tu entorno Java y Maven e iniciará el servidor.
   - **Opción B (Depurador VS Code)**:
     Presiona `F5` o abre `MainApplication.java` y haz clic en el botón `Run` que aparece sobre el método `main`.

---

## ⚙️ Requisitos Previos

- **Java Development Kit (JDK)**: 17 o 21+.
- **Maven**: 3.8+ (incluido Maven Wrapper `mvnw.cmd` / `mvnw`).

---

## 🏃 Cómo Ejecutar con Maven en Terminal

```bash
# En Windows (PowerShell o CMD)
mvn spring-boot:run
# O usando el wrapper:
.\\mvnw.cmd spring-boot:run

# En Linux o macOS
./mvnw spring-boot:run
```

---

## 📡 Documentación Interactiva (Swagger UI) y Consola H2

Una vez iniciada la aplicación en el puerto `8080`:
- **Swagger UI (Pruebas Interactivas)**: [http://localhost:8080/swagger-ui.html](http://localhost:8080/swagger-ui.html)
- **OpenAPI Schema JSON**: [http://localhost:8080/v3/api-docs](http://localhost:8080/v3/api-docs)
- **Consola de Base de Datos H2**: [http://localhost:8080/h2-console](http://localhost:8080/h2-console)
  - JDBC URL: `jdbc:h2:mem:classforgedb`
  - Usuario: `sa`
  - Contraseña: *(en blanco)*

---

## 📡 Endpoints de la API REST

Todos los endpoints base están prefijados bajo `/api/v1/`:
{endpoints_list}

---

## 📱 Integración con Clientes Móviles (Flutter / React Native) y Web

Este backend incluye configuración de **CORS** pre-habilitada:
- Para **Emulador Android**: Usa `http://10.0.2.2:8080/api/v1/...`
- Para **Simulador iOS / Navegador Web**: Usa `http://localhost:8080/api/v1/...`
- Para **Dispositivos Físicos (LAN)**: Usa `http://TU_IP_LOCAL:8080/api/v1/...`
"""

VSCODE_LAUNCH_JSON = """{{
    "version": "0.2.0",
    "configurations": [
        {{
            "type": "java",
            "name": "Spring Boot - MainApplication",
            "request": "launch",
            "mainClass": "{package_name}.MainApplication",
            "projectName": "classforge-generated-backend",
            "env": {{
                "SPRING_PROFILES_ACTIVE": "dev"
            }}
        }}
    ]
}}
"""

VSCODE_SETTINGS_JSON = """{{
    "java.configuration.updateBuildConfiguration": "automatic",
    "java.compile.nullAnalysis.mode": "automatic",
    "editor.formatOnSave": true,
    "editor.tabSize": 4,
    "files.exclude": {{
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true
    }}
}}
"""

VSCODE_EXTENSIONS_JSON = """{{
    "recommendations": [
        "vscjava.vscode-java-pack",
        "vmware.vscode-spring-boot",
        "vmware.vscode-boot-dev-pack",
        "vscjava.vscode-lombok"
    ]
}}
"""

RUN_BAT = """@echo off
setlocal enabledelayedexpansion

echo ===================================================
echo   ClassForge Spring Boot 3 - Runner para VS Code / Windows
echo ===================================================

:: 1. Verificacion de Java
where java >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo [INFO] Java encontrado en el sistema.
) else (
    echo [INFO] Java no encontrado en PATH global. Buscando JDK local...
    if exist "C:\\Program Files\\Android\\Android Studio\\jbr\\bin\\java.exe" (
        set "JAVA_HOME=C:\\Program Files\\Android\\Android Studio\\jbr"
        set "PATH=!JAVA_HOME!\\bin;!PATH!"
        echo [INFO] Utilizando OpenJDK de Android Studio JBR.
    ) else if exist "%ProgramFiles%\\Java" (
        for /d %%D in ("%ProgramFiles%\\Java\\*") do (
            if exist "%%D\\bin\\java.exe" (
                set "JAVA_HOME=%%D"
                set "PATH=!JAVA_HOME!\\bin;!PATH!"
                echo [INFO] JDK detectado en %%D.
            )
        )
    )
)

where java >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] No se pudo encontrar Java JDK 17 o superior.
    echo Por favor instala Java o abre la carpeta en VS Code con la extension "Extension Pack for Java".
    pause
    exit /b 1
)

:: 2. Ejecucion con Maven o Wrapper
where mvn >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo [INFO] Iniciando aplicacion Spring Boot con Maven local...
    call mvn spring-boot:run
) else if exist "mvnw.cmd" (
    echo [INFO] Iniciando aplicacion Spring Boot con Maven Wrapper...
    call mvnw.cmd spring-boot:run
) else (
    echo [INFO] Maven no detectado en PATH.
    echo [TIP] Puedes abrir este proyecto en VS Code y presionar F5 (o hacer clic en Run sobre MainApplication.java).
    pause
)
"""

RUN_SH = """#!/bin/bash
echo "==================================================="
echo "  ClassForge Spring Boot 3 - Runner Linux / macOS  "
echo "==================================================="

if command -v mvn &> /dev/null; then
    echo "[INFO] Ejecutando con Maven..."
    mvn spring-boot:run
elif [ -f "./mvnw" ]; then
    echo "[INFO] Ejecutando con Maven Wrapper..."
    chmod +x ./mvnw
    ./mvnw spring-boot:run
else
    echo "[INFO] Maven no encontrado. Instala Maven o abre el proyecto en VS Code con la extension Java."
    exit 1
fi
"""

MVNW_CMD = """@echo off
setlocal
where mvn >nul 2>&1
if %ERRORLEVEL% equ 0 (
    mvn %*
    exit /b %ERRORLEVEL%
)

set "MAVEN_DIR=%USERPROFILE%\\.classforge\\maven\\apache-maven-3.9.6"
if not exist "%MAVEN_DIR%\\bin\\mvn.cmd" (
    echo [ClassForge Maven Wrapper] Preparando Maven portable para ejecucion inmediata...
    powershell -Command "New-Item -ItemType Directory -Force -Path '%USERPROFILE%\\.classforge\\maven' | Out-Null; Invoke-WebRequest -Uri 'https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip' -OutFile '%USERPROFILE%\\.classforge\\maven\\mvn.zip'; Expand-Archive -Path '%USERPROFILE%\\.classforge\\maven\\mvn.zip' -DestinationPath '%USERPROFILE%\\.classforge\\maven' -Force"
)

if exist "%MAVEN_DIR%\\bin\\mvn.cmd" (
    "%MAVEN_DIR%\\bin\\mvn.cmd" %*
) else (
    echo [ERROR] No se pudo inicializar Maven. Ejecuta desde VS Code o instala Maven.
)
"""

MVNW_SH = """#!/bin/bash
if command -v mvn &> /dev/null; then
    exec mvn "$@"
fi

MAVEN_DIR="$HOME/.classforge/maven/apache-maven-3.9.6"
if [ ! -f "$MAVEN_DIR/bin/mvn" ]; then
    echo "[ClassForge Maven Wrapper] Descargando Maven portátil..."
    mkdir -p "$HOME/.classforge/maven"
    curl -sS -L -o "$HOME/.classforge/maven/mvn.tar.gz" "https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz"
    tar -xzf "$HOME/.classforge/maven/mvn.tar.gz" -C "$HOME/.classforge/maven/"
fi

if [ -f "$MAVEN_DIR/bin/mvn" ]; then
    exec "$MAVEN_DIR/bin/mvn" "$@"
else
    echo "Error ejecutando Maven. Por favor instala Maven en tu sistema."
    exit 1
fi
"""


